
import React from 'react'

export async function generateMetadata({ params, searchParams }) {
    console.log(params)
    return {
        title: "Products Detail Page: Product " + params.id,
        description: "Generated by Iphone Products " + searchParams.q,
    }
}

const ProductID = (p) => {

    return (
        <div>Product Detail {p.id}</div>
    )
}

export default ProductID